#!/usr/bin/env bash
# this is a bash script install nginx on a server

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw 'Nginx HTTP'

echo "Hello World" | sudo tee /var/www/html/index.html
sudo nginx -t
sudo service nginx restart
