#!/usr/bin/env bash
# this is a bash script install nginx on a server

sudo apt-get update
sudo apt-get install -y nginx
sudo ufw 'Nginx HTTP'
sudo chown -R ubuntu /var/www
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo nginx -t
sudo service nginx restart
