#!/bin/env bash
# this script configures nginx with a redirection page

sudo apt-get update
sudo apt-get install -y nginx
sudo sed -i '/server_name _;/a \\n # Redirect /redirect me to a new page\n location = /redirect_me {\n        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n  }' /etc/nginx/sites-available/default

sudo nginx -t
sudo service nginx restart
