#!/usr/bin/env bash
# this script configures nginx with a redirection page

ADD301_REDIRECT="\trewrite ^\/redirect_me https:\/\/www.github.com\/olami928 permanent;"

sudo apt-get update
sudo apt-get install -y nginx
sudo chown -R ubuntu /var/www
echo "Hello World!" | /var/www/html/index.nginx-debian.html
sudo sed -i "s/server_name _; $ADD301_REDIRECT" /etc/nginx/sites-available/default
sudo service nginx restart
