#!/usr/bin/env bash
# this script configures nginx with a redirection page

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html
ADD301_REDIRECT="\n\trewrite ^\/redirect_me https:\/\/www.github.com\/olami928 permanent;"

sudo sed -i "s/server_name -;/$ADD301_REDIRECT/" /etc/nginx/sites-enabled/default

sudo service nginx restart
