#!/usr/bin/env bash
# 404 Not Found Page
# returns a custom header on request

apt-get update
apt-get install -y nginx
sudo apt-get -y update
sudo apt-get -y install nginx

touch /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;
    root   /var/www/html/;
    index  index.html index.htm;
sudo sed -i "6i\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
}" > /etc/nginx/sites-available/default

service nginx restart
sudo service nginx start
