#!/usr/bin/env bash
# 404 Not Found Page
# Returns a custom header on request

# Update and install Nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Create and populate index.html
echo "Hello World!" | sudo tee /var/www/html/index.html

# Add a custom header to the Nginx configuration
sudo sed -i "6i\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default

# Create a custom 404 error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Restart Nginx to apply changes
sudo service nginx restart
