#!/usr/bin/env bash
# configuring web-01 

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

new_string="server_name -;\n\trewrite ^\/redirect_me https://github.com\/olami928 permanent;"

sudo sed -i "s/server-name;/$new_string/" /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

sudo sed -i "server_name -;/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

sudo nginx -t
sudo service nginx restart
