#!/usr/bin/env bash
# this code printd an ip address
if [$# -ne 1]; then
	echo "Usage: $0 {IP_ADDRESS}"
else
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
	exit 1
fi
ip_address="$1"
ping -c 5 "$ip_address"
