#!/usr/bin/env bash
# this program does the fizzbuzz test

count=1

while [[ "$count" -le 100 ]]; do
	if [[ (($count % 3)) == 0 && $count % 5 == 0 ]]; then
		echo "FizzBuzz"
	elif [[ $count % 3 == 0 && $count % 5 != 0 ]]
		echo "Fizz"
	elif [[ $count % 3 != 0 && $count % 5 == 0 ]]
		echo "Buzz"
	else
		echo "$count"
	fi
	((count++))
done
