#!/usr/bin/env bash
# This program prints "Best School"

count=0  # Corrected assignment format

until [ "$count" -gt 10 ]  # Corrected condition
do
        echo "Best School"
        ((count++))
done
