#!/usr/bin/env bash
# This script checks for the existence and properties of a file named 'school'

FILE="school"

if [[ -e $FILE ]]; then
    echo "school file exists"
    
    if [[ -s $FILE ]]; then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi
    
    if [[ -f $FILE ]]; then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
