#!/usr/bin/env bash
# this script installs ufw

sudo apt install -y ufw
sudo ufw default allowing outgoing
sudo ufw default deny incoming
sudo ufw allow 22
sudo ufw allow 443
sudo ufw allow 80
echo "y" | sudo ufw enable
